package shops

/*import (
	"fmt"
	"github.com/fatih/structs"
	"github.com/go-chi/chi"
	"html/template"
	"log"
	"net/http"
	"os"
	"path"
	"strconv"
)

// GetAllProducts fetches all products in my shop
func GetAllProducts(w http.ResponseWriter, r *http.Request) {
	t := template.New("index.html") // Create a template.
	cwd, _ := os.Getwd()
	p := path.Join(cwd, "public", "index.html")
	t, err := t.ParseFiles(p) // Parse template file.
	if err != nil {
		log.Println(err)
	}

}

// GetProduct handler for fetching a particular product
func PostProduct(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	fmt.Print(id)
	if err != nil {
		log.Println(err)
		return
	}


	product, err := AutoGenerated{}.Get(id)
	if err != nil {
		log.Println(err)
	}

	pm := &AutoGenerated{product.Timestamp, product.QualiaID, product.PlateNumber,product.DeviceID,product.Version,product.AdvertisementID,product.EmojiStatus,product.InfoCount,product.BatteryLevel,product.GatewayID,product.Location}

	Insert(structs.Map(pm))
}*/
