package main

import (
	"fmt"
	"github.com/fatih/structs"
	"github.com/labstack/echo/v4"
	// cool logger package
	"influxdb2/main/modules/shops"
	"net/http"
)

func main() {

	e := echo.New()
	e.POST("/users", func(c echo.Context) (err error) {
		//
		u := new(shops.AutoGenerated)
		fmt.Print("run api")
		if err = c.Bind(u); err != nil {
			return
		}
		/*http.HandleFunc("/h1", shops.PostProduct)*/
		shops.Insert(structs.Map(u))
		return c.JSON(http.StatusOK, u)

	})
	e.Logger.Fatal(e.Start(":1323"))

	/*r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	e.POST("/product", func(c echo.Context) (err error) {

		//
		u := new(shops.AutoGenerated)

		//shops.Insert(u)

		if err = c.Bind(u); err != nil {
			return
		}

		return c.JSON(http.StatusOK, u)


	})*/
}

